### ISSUE TITLE
Roadmap for v5

### ISSUE THREAD

**Issue by BenMorel** [spatie/crawler#243]
I'm creating this issue to keep track of the tasks for v5.

## New features

- [ ] proper support for persistent (database-backed) queues (#137, #200), allowing to perform a crawl in discrete steps at different points in time, and resume an interrupted crawl; note that this would benefit a lot from #237 (putting a failed URL back onto the persistent crawl queue) if you're willing to revisit this
- [ ] automatically set the `Referer` header
- [ ] (to be discussed) ship a PDO implementation of a database-backed crawl queue, which would also serve as a reference implementation

## Fixes

- [ ] fix the performance issues (#210, #241, and as a result, #236) (positive side effect: removing one dependency)

## Code improvements

- [X] Get rid of `$id` in `CrawlUrl`: Guzzle's `Pool` [can yield string keys](https://github.com/guzzle/guzzle/pull/1203) as well, we do not need an int, and can use the URL as the key to greatly simplify the code - **implemented** in #244
- [ ] Improve performance of `CollectionCrawlQueue` by using an indexed array rather than [looping through the URLs](https://github.com/spatie/crawler/blob/67974a810f6a342c333c4e348fcfad7c1375ffde/src/CrawlQueue/CollectionCrawlQueue.php#L103-L117)
- [ ] Add return types wherever possible (example: `CrawlQueue::getFirstPendingUrl() : ?CrawlUrl`)
- [ ] Change signature of `CrawlQueue::has` to `(CrawlUrl $crawlUrl)` to be consistent with the other methods
- [ ] Decouple `CrawlRequestFailed|FulfilledClass` from Guzzle by replacing it with an interface; this will allow better static analysis than a invokable class name, and make the contract more explicit, such as: `public function crawlFailed(RequestException $exception, CrawlUrl $url)`
- [ ] Make `CrawlProfile` an interface instead of an abstract class

## Cleanup

- [ ] remove deprecated methods (`Crawler::endsWith()`)
- [ ] If possible, get rid of `CrawlQueue::get()`, introduced in #244 as a temporary workaround for Guzzle's inability to use objects as keys

**Comment by brendt** [comment]
Thanks Ben for the effort you've already put into this, much appreciated 👏

You mentioned that a `v5` branch would still be helpful, there's a `v5-wip`, which I just rebased on master. I'll try my best to keep it up to date, and suggest you target that branch.

**Comment by brendt** [comment]
Also, let me know when you need input or want help with anything.

**Comment by BenMorel** [comment]
Hi @brendt, thank you, @freekmurze has already retargeted #244 on `v5-wip`; I'm currently waiting for feedback on this first PR before moving forward with changes!

Note that the [comment](https://github.com/spatie/crawler/pull/244#issuecomment-506333854) I've left does not prevent from moving forward, I can still improve it later if I come up with a solution to further simplify it.

**Comment by brendt** [comment]
I'll be reviewing #244 later this week!

**Comment by m1guelpf** [comment]
Hey! How can I help move v5 forward?

**Comment by BenMorel** [comment]
Hi @m1guelpf , I should start working again on this in the coming weeks. Please feel free to submit a PR if you think you can work on any on the points above!

**Comment by BenMorel** [comment]
Could you please reopen?

I've been working on another project over the past few months, but will be coming back here soon to resume work on v5.

**Comment by freekmurze** [comment]
👍

**Comment by akalongman** [comment]
How I liked the idea about v5..

**Comment by BenMorel** [comment]
@akalongman Unfortunately, I stopped working on the project that required the features above for the time being. I may come back to it at some point, because I don’t like unfinished business, but probably not in a near future. The roadmap above still stands though, if someone is willing to help. I’ll keep an eye here and can help coordinate the effort.
